# Answer 1

In [6]:
import numpy as np
x=np.random.rand(10,1)
print(x)
x.mean()



[[0.0864862 ]
 [0.69169492]
 [0.62472626]
 [0.16859194]
 [0.28266514]
 [0.17851676]
 [0.69571398]
 [0.29413577]
 [0.81975768]
 [0.82149464]]


0.4663783306366871

# Answer 2

In [11]:
import numpy as np
x=np.random.rand(10,1)
print(x)
x.var()
x.std()

[[0.87978915]
 [0.2338819 ]
 [0.67356894]
 [0.31129029]
 [0.97526439]
 [0.92038669]
 [0.77560536]
 [0.72863085]
 [0.66497553]
 [0.78004373]]


0.23228743079181194

# Answer 3

In [33]:
import numpy as np
x=np.random.rand(10,20)
y=np.random.rand(20,25)
print(x,y)

[[0.3837197  0.81247264 0.18302626 0.13004674 0.29560766 0.45321919
  0.21300086 0.34764832 0.20799453 0.66066955 0.77926038 0.72726106
  0.22154946 0.16146338 0.51084816 0.37162763 0.05150852 0.01130777
  0.2068882  0.09011326]
 [0.79062266 0.25777846 0.54832675 0.23764095 0.80094445 0.07020816
  0.82217938 0.65634178 0.86099811 0.81242472 0.36118169 0.55064802
  0.92882501 0.96794989 0.59264733 0.15325853 0.0407713  0.22438083
  0.14394992 0.38913019]
 [0.58130729 0.37122039 0.87800138 0.18966198 0.0775108  0.98823046
  0.09827627 0.39061621 0.56008465 0.09487746 0.43542177 0.65063269
  0.44533482 0.61695646 0.40279273 0.6747056  0.95869639 0.48364156
  0.78151663 0.24562479]
 [0.05766956 0.05998935 0.74838576 0.44875552 0.75256259 0.08169526
  0.13336503 0.59850333 0.829752   0.10624614 0.99578605 0.80886279
  0.65113797 0.71605785 0.29960264 0.77987244 0.85057007 0.35887603
  0.23371824 0.19053752]
 [0.1568789  0.5383279  0.05938895 0.42127099 0.06608165 0.26286123
  0.70272579 0.6

In [34]:
A=np.matmul(x,y)

array([[3.61786911, 3.75514251, 3.64313314, 4.36184066, 2.68223385,
        3.6485746 , 3.59914869, 3.00318986, 2.32398922, 4.00841824,
        2.8566923 , 2.79446487, 3.73708156, 4.21165266, 3.04998331,
        3.98830943, 3.57384033, 2.80963354, 2.8503293 , 2.42298177,
        3.68300957, 4.19968441, 2.66319773, 2.90648162, 3.93534498],
       [5.2224027 , 5.66689254, 4.80173876, 6.46233043, 4.57313969,
        5.60448991, 4.920828  , 5.10968224, 3.99489511, 5.05668901,
        4.75317764, 4.06086189, 5.47066866, 5.718029  , 4.76823795,
        6.21245577, 4.20595382, 5.04900203, 4.63598721, 5.17286942,
        5.88466165, 6.6725923 , 4.08580025, 4.27142978, 6.43717586],
       [4.54150357, 4.9254918 , 4.61266553, 5.59325911, 4.15709863,
        5.36657471, 4.63736449, 4.01765723, 3.46709507, 5.34223877,
        4.78157276, 3.71572433, 6.0466266 , 5.0813537 , 5.28157942,
        5.35773943, 4.2123094 , 3.86624579, 4.3147115 , 3.31753093,
        5.28367876, 6.00314465, 4.51547354, 4.

In [35]:
print(A)

[[5.75081816 5.44042922 3.53010245 5.59721527 4.90962492 5.24301148
  5.45911802 4.78823054 4.93366784 4.53483335 4.23721244 6.01554727
  4.9759196  6.44151147 4.60553667 5.05955376 3.56677123 4.40960578
  5.26787228 4.89550415 4.19302931 5.94316825 5.81226804 5.59794694
  4.86912494]
 [5.5650591  5.52969928 4.1941144  4.95232635 4.41038053 5.76764101
  5.27426279 4.68106552 5.09207338 4.81153067 4.17808154 6.22118485
  4.45407839 5.87077078 4.86718906 5.17117045 3.61444675 5.15504416
  5.21099771 4.81423401 3.93057731 5.95346591 5.34749846 5.84091832
  4.42016029]
 [6.28193894 5.76729117 3.93713907 6.82228919 4.91856855 5.88636409
  5.90686056 4.5531938  5.43332269 5.34823375 5.71149572 6.7828859
  5.92456543 7.30174667 4.78564097 5.69742214 3.3811359  5.33963683
  6.56819753 6.13771108 5.17344674 6.49465112 5.70550602 5.27564659
  4.69662855]
 [5.00083754 5.52826082 3.50997057 5.5021075  4.14991468 5.56556612
  5.24131296 4.82232568 4.99736519 5.06979588 5.53480436 5.71201706
  5.533

In [37]:
A=np.matmul(x,y)
print(A)

[[3.61786911 3.75514251 3.64313314 4.36184066 2.68223385 3.6485746
  3.59914869 3.00318986 2.32398922 4.00841824 2.8566923  2.79446487
  3.73708156 4.21165266 3.04998331 3.98830943 3.57384033 2.80963354
  2.8503293  2.42298177 3.68300957 4.19968441 2.66319773 2.90648162
  3.93534498]
 [5.2224027  5.66689254 4.80173876 6.46233043 4.57313969 5.60448991
  4.920828   5.10968224 3.99489511 5.05668901 4.75317764 4.06086189
  5.47066866 5.718029   4.76823795 6.21245577 4.20595382 5.04900203
  4.63598721 5.17286942 5.88466165 6.6725923  4.08580025 4.27142978
  6.43717586]
 [4.54150357 4.9254918  4.61266553 5.59325911 4.15709863 5.36657471
  4.63736449 4.01765723 3.46709507 5.34223877 4.78157276 3.71572433
  6.0466266  5.0813537  5.28157942 5.35773943 4.2123094  3.86624579
  4.3147115  3.31753093 5.28367876 6.00314465 4.51547354 4.69792269
  5.20310418]
 [4.91526823 5.23408134 4.77559742 5.63616522 4.20454815 5.25906983
  4.74323805 4.87309998 3.26028357 5.45295134 3.89667228 3.59272173
  5.172

In [39]:
A=np.matmul(x,y)
print(A)

[[3.61786911 3.75514251 3.64313314 4.36184066 2.68223385 3.6485746
  3.59914869 3.00318986 2.32398922 4.00841824 2.8566923  2.79446487
  3.73708156 4.21165266 3.04998331 3.98830943 3.57384033 2.80963354
  2.8503293  2.42298177 3.68300957 4.19968441 2.66319773 2.90648162
  3.93534498]
 [5.2224027  5.66689254 4.80173876 6.46233043 4.57313969 5.60448991
  4.920828   5.10968224 3.99489511 5.05668901 4.75317764 4.06086189
  5.47066866 5.718029   4.76823795 6.21245577 4.20595382 5.04900203
  4.63598721 5.17286942 5.88466165 6.6725923  4.08580025 4.27142978
  6.43717586]
 [4.54150357 4.9254918  4.61266553 5.59325911 4.15709863 5.36657471
  4.63736449 4.01765723 3.46709507 5.34223877 4.78157276 3.71572433
  6.0466266  5.0813537  5.28157942 5.35773943 4.2123094  3.86624579
  4.3147115  3.31753093 5.28367876 6.00314465 4.51547354 4.69792269
  5.20310418]
 [4.91526823 5.23408134 4.77559742 5.63616522 4.20454815 5.25906983
  4.74323805 4.87309998 3.26028357 5.45295134 3.89667228 3.59272173
  5.172

In [15]:
import numpy as npimp
x=np.random.rand(10,20)
y=np.random.rand(20,25)
print(x,y)
A=np.matmul(x,y)
print(A)
A.reshape(10,25)
A.sum()

[[7.89851185e-01 8.15136696e-01 7.45521508e-01 5.09787065e-01
  9.42093083e-01 5.10051101e-01 4.86690531e-01 1.32637718e-01
  7.58433794e-01 1.13347736e-02 7.94076898e-01 7.48465104e-01
  5.61985097e-02 8.54262576e-01 7.86627368e-01 2.04079738e-01
  7.34955961e-01 5.84933929e-01 3.08377504e-01 8.06602609e-01]
 [1.14167961e-01 6.04899769e-01 8.22469728e-01 2.38070328e-01
  5.17282698e-02 5.79318385e-03 7.01129110e-01 3.94061689e-01
  7.55764399e-01 2.19777345e-01 1.88150594e-01 1.90960829e-01
  7.25542739e-01 3.62713461e-03 1.98770389e-01 4.76680671e-01
  6.34334530e-01 1.79944885e-01 9.56801288e-01 2.74805115e-01]
 [8.27683260e-01 5.46760757e-02 7.07194395e-02 3.69453558e-01
  1.72850169e-01 1.59594888e-01 8.72087690e-01 1.50077606e-01
  8.11631180e-01 9.60740946e-01 3.10761504e-01 2.85938518e-01
  3.99236591e-01 2.30062258e-01 1.02601684e-01 9.81769726e-01
  6.75737213e-01 2.66666139e-01 8.24381520e-01 1.94517594e-01]
 [3.74325139e-01 3.09294652e-01 9.99656950e-01 5.39913763e-01
  4.8

1213.527747505015

# Answer 4

In [16]:
import numpy as np
x =np.random.rand(10,1)
print(x)

[[0.53357939]
 [0.29622876]
 [0.58593605]
 [0.02996134]
 [0.00299636]
 [0.52859486]
 [0.52397185]
 [0.3246335 ]
 [0.22614854]
 [0.805276  ]]


In [17]:
B = arrayfun(f(x)=1 / (1 + exp(-x)) 
,x)

SyntaxError: keyword can't be an expression (<ipython-input-17-ca77895d766e>, line 1)